addpath('recode/matlab');

frames = repmat(struct(...
    'frame_index', 0, ...
    'left_hip_angle', 0, ...
    'right_hip_angle', 0, ...
    'left_knee_angle', 0, ...
    'right_knee_angle', 0, ...
    'left_ankle_angle', 0, ...
    'right_ankle_angle', 0, ...
    'trunk_angle', 0, ...
    'pelvis_tilt', 0, ...
    'landmark_positions', struct('left_ankle', [0,0,0], 'right_ankle', [0,0,0]) ...
), 40, 1);

for i = 1:numel(frames)
    frames(i).frame_index = i - 1;
end

methods = gaitkit.listMethods()
result = gaitkit.detect('bayesian_bis', frames, 100, struct('position','mm','angles','deg'))
