% Example usage for the MATLAB wrapper.
% Run this script from anywhere; it resolves the wrapper path automatically.

thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);

if count(py.sys.path, '') == 0
    insert(py.sys.path, int32(0), '');
end

try
    py.importlib.import_module('gaitkit');
catch ME
    error(['Python module ''gaitkit'' is not available in current pyenv. ', ...
           'Run gaitkit.installPythonBackend() first. Original error: %s'], ME.message);
end

frames = repmat(struct(...
    'frame_index', 0, ...
    'left_hip_angle', 0, ...
    'right_hip_angle', 0, ...
    'left_knee_angle', 0, ...
    'right_knee_angle', 0, ...
    'left_ankle_angle', 0, ...
    'right_ankle_angle', 0, ...
    'trunk_angle', 0, ...
    'pelvis_tilt', 0, ...
    'landmark_positions', struct('left_ankle', [0,0,0], 'right_ankle', [0,0,0]) ...
), 40, 1);

for i = 1:numel(frames)
    frames(i).frame_index = i - 1;
end

methods = gaitkit.listMethods();
disp(methods);

result = gaitkit.detect('bayesian_bis', frames, 100, struct('position','mm','angles','deg'));
disp(result);
